// ============================================================
// siteData.ts — AUTO-GENERATED by site_generator.py
// Do not edit manually. Re-run the generator to update.
// ============================================================

export type Variant = 'A' | 'B' | 'C' | 'D'

export interface ServiceItem {
  iconName: string
  name: string
  description: string
}

export interface ReviewItem {
  name: string
  rating: number
  text: string
  date: string
}

export interface WhyUsPoint {
  heading: string
  body: string
}

export interface ProcessStep {
  heading: string
  body: string
}

export interface FAQItem {
  question: string
  answer: string
}

export interface SiteData {
  businessName: string
  trade: string
  tagline: string
  phone: string
  email: string
  address: string
  city: string
  serviceArea: string
  googleBusinessUrl: string
  yearsExperience: number
  bookingUrl?: string
  variant: Variant
  hero: {
    heading: string
    subheading: string
    primaryCta: string
    secondaryCta: string
  }
  services: ServiceItem[]
  trustItems: string[]
  whyUs: {
    heading: string
    subheading: string
    points: WhyUsPoint[]
  }
  process: ProcessStep[]
  faqs: FAQItem[]
  reviews: ReviewItem[]
  seo: {
    title: string
    description: string
    canonicalUrl: string
  }
}

const siteData: SiteData = {
  businessName: 'Sterling Roofing Contractors Ltd. - Manchester',
  trade: 'Roofers',
  tagline: 'Manchester\'s Trusted Roofing Contractors',
  phone: '+44 161 390 0513',
  email: 'fenlandpavingandresin@gmail.com',
  address: 'Sir Gerald Kaufman Cl, Manchester M18 7DW, United Kingdom',
  city: 'Manchester',
  serviceArea: 'Manchester',
  googleBusinessUrl: 'https://maps.google.com',
  yearsExperience: 23,

  variant: 'D',

  hero: {
    heading: 'Professional Roofing Services in Manchester',
    subheading: 'Sterling Roofing Contractors Ltd. provides reliable roofing solutions across Manchester with 12 years of experience. From repairs to complete replacements, we deliver quality workmanship you can trust.',
    primaryCta: 'Get a Free Quote',
    secondaryCta: 'Call Now',
  },

  services: [
    {
      iconName: 'Roof',
      name: 'Roof Repairs',
      description: 'We fix leaks, damaged tiles, and structural issues quickly and efficiently. Our repairs come with a guarantee for complete peace of mind.',
    },
    {
      iconName: 'Home',
      name: 'New Roof Installation',
      description: 'Complete roof replacements using high-quality materials and expert craftsmanship. We work with all roof types including slate, tile, and flat roofing systems.',
    },
    {
      iconName: 'Shield',
      name: 'Roof Maintenance',
      description: 'Regular maintenance checks to prevent costly problems before they start. We clean gutters, check for damage, and ensure your roof stays in perfect condition.',
    },
    {
      iconName: 'Droplets',
      name: 'Guttering Services',
      description: 'Professional gutter installation, repair, and cleaning services throughout Manchester. We ensure proper drainage to protect your property from water damage.',
    },
    {
      iconName: 'RefreshCw',
      name: 'Roof Restoration',
      description: 'Restore your existing roof to like-new condition without full replacement costs. Our restoration services extend roof life and improve your property\'s appearance.',
    },
    {
      iconName: 'Search',
      name: 'Roof Inspections',
      description: 'Thorough roof surveys to identify potential issues and provide honest assessments. We provide detailed reports with clear recommendations and fair pricing.',
    },
  ],

  trustItems: [
    '12+ Years Experience',
    'Fully Insured',
    'Free Quotes',
    'Local to Manchester'
  ],

  whyUs: {
    heading: 'Why Choose Sterling Roofing Contractors Ltd.?',
    subheading: 'With 12 years of experience and a perfect 5-star rating from satisfied Manchester customers, we\'re the roofing contractors you can rely on for quality and service.',
    points: [
      {
        heading: 'Local Expertise',
        body: 'Based in Manchester, we understand local weather challenges and building requirements. Our team knows exactly what works best for properties in our area.',
      },
      {
        heading: 'Quality Guaranteed',
        body: 'All our work comes with comprehensive guarantees and we use only premium materials. Your satisfaction and peace of mind are our top priorities.',
      },
      {
        heading: 'Fully Insured',
        body: 'Complete public liability insurance protects both you and our workers. We\'re fully qualified and certified for all types of roofing work.',
      },
      {
        heading: 'Fair Pricing',
        body: 'Transparent quotes with no hidden costs or surprise charges. We believe in honest pricing and delivering excellent value for money.',
      },
    ],
  },

  process: [
    {
      heading: 'Contact Our Team',
      body: 'Call us or request a quote online to discuss your roofing needs. We\'ll arrange a convenient time to visit your property and assess the work required.',
    },
    {
      heading: 'Free Survey',
      body: 'Our experienced roofers will inspect your roof and provide a detailed assessment. You\'ll receive a clear, written quote with no obligation to proceed.',
    },
    {
      heading: 'Quality Work',
      body: 'Once you approve the quote, our skilled team completes the work to the highest standards. We use premium materials and proven techniques for lasting results.',
    },
    {
      heading: 'Final Inspection',
      body: 'We conduct a thorough final check and clean up completely before handover. Your guarantee documentation and aftercare advice are provided with every job.',
    },
  ],

  faqs: [
    {
      question: 'How quickly can you start work on my roof?',
      answer: 'We typically schedule most roofing jobs within 7-14 days of your quote approval. Emergency repairs can often be arranged within 24-48 hours depending on the severity of the issue.',
    },
    {
      question: 'Do you provide guarantees on your roofing work?',
      answer: 'Yes, all our work comes with comprehensive guarantees covering both materials and workmanship. The length varies depending on the type of work, with full details provided in your quote.',
    },
    {
      question: 'What areas of Manchester do you cover?',
      answer: 'We provide roofing services throughout Manchester and surrounding areas. Our local base means we can respond quickly to both routine work and emergency repairs.',
    },
    {
      question: 'Are your quotes really free with no obligation?',
      answer: 'Absolutely. We provide detailed written quotes at no cost and with no pressure to proceed. Our quotes are valid for 30 days and include a full breakdown of all costs.',
    },
    {
      question: 'What types of roofing materials do you work with?',
      answer: 'We work with all roofing materials including slate, clay and concrete tiles, flat roofing systems, and lead work. We\'ll recommend the best options for your property and budget.',
    },
    {
      question: 'Do you handle insurance claims for roof damage?',
      answer: 'Yes, we regularly work with insurance companies and can assist with storm damage claims. We provide detailed reports and work directly with assessors to simplify the process for you.',
    },
  ],

  reviews: [
    {
      name: 'Sarah M.',
      rating: 5,
      text: 'Brilliant service from Sterling Roofing. They fixed our leaking roof quickly and the price was very reasonable. Would definitely recommend them to anyone in Manchester.',
      date: 'October 2024',
    },
    {
      name: 'David K.',
      rating: 5,
      text: 'Professional team who arrived on time and completed our new roof installation exactly as promised. The quality of work is excellent and they cleaned up perfectly afterwards.',
      date: 'September 2024',
    },
    {
      name: 'Emma T.',
      rating: 5,
      text: 'Really impressed with their honesty and expertise. They could have sold us a complete new roof but instead repaired what needed fixing. Trustworthy local roofers.',
      date: 'August 2024',
    },
  ],

  seo: {
    title: 'Sterling Roofing Contractors Ltd. | Roofers in Manchester',
    description: 'Professional roofing services in Manchester. 12 years experience, 5-star rated, fully insured. Roof repairs, installations & maintenance. Call +44 161 390 0513.',
    canonicalUrl: 'https://preview-sterling-roofing-contractors-ltd-manchester.vercel.app',
  },
}

export default siteData

// CSS custom properties injected by site_generator.py
// These override :root variables in index.css at runtime
export const siteTheme = {
  '--color-primary':  '#1B2D45',
  '--color-accent':   '#E85D26',
  '--color-bg':       '#FAFAF8',
  '--color-text':     '#1A1A1A',
  '--color-muted':    '#6B7280',
  '--color-border':   '#E5E5E5',
  '--font-heading':   "'Instrument Serif', Georgia, serif",
  '--font-body':      "'DM Sans', system-ui, sans-serif",
}
